<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>pl.mbaracz</groupId>
        <artifactId>jwebsockets</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>jwebsockets-jackson</artifactId>

    <properties>
        <maven.javadoc.skip>false</maven.javadoc.skip>
        <maven.source.skip>false</maven.source.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>pl.mbaracz</groupId>
            <artifactId>jwebsockets-core</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
